#!/bin/bash

for entity_name in $(
  curl -k -s \
    --header "X-Vault-Token: $VAULT_TOKEN" \
    --request LIST \
    $VAULT_ADDR/v1/identity/entity/name | jq -r .data.keys[]
)
do
  curl -k -s \
    --header "X-Vault-Token: $VAULT_TOKEN" \
    $VAULT_ADDR/v1/identity/entity/name/$entity_name | jq -r .data.aliases[].mount_accessor
done | sort | uniq -c | sort -n

